# coding: utf-8

"""
    HIU API SDK

    Health Information User API for handling consent and health information requests.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from abdm-hiu-sdk.abdm-hiu-sdk.model.list_consent_artefacts200_response_model import ListConsentArtefacts200ResponseModel

class TestListConsentArtefacts200ResponseModel(unittest.TestCase):
    """ListConsentArtefacts200ResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListConsentArtefacts200ResponseModel:
        """Test ListConsentArtefacts200ResponseModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListConsentArtefacts200ResponseModel`
        """
        model = ListConsentArtefacts200ResponseModel()
        if include_optional:
            return ListConsentArtefacts200ResponseModel(
                consent_artefacts = [
                    null
                    ]
            )
        else:
            return ListConsentArtefacts200ResponseModel(
        )
        """

    def testListConsentArtefacts200ResponseModel(self):
        """Test ListConsentArtefacts200ResponseModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
