# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_auth_notify_v05_users_auth_notify_post(self) -> None:
        """Test case for auth_notify_v05_users_auth_notify_post

        Auth Notify
        """
        pass

    def test_confirm_auth_v05_users_auth_confirm_post(self) -> None:
        """Test case for confirm_auth_v05_users_auth_confirm_post

        Confirm Auth
        """
        pass

    def test_consent_hiu_notify_v05_consents_hiu_notify_post(self) -> None:
        """Test case for consent_hiu_notify_v05_consents_hiu_notify_post

        Consent Hiu Notify
        """
        pass

    def test_fetch_auth_modes_v05_users_auth_fetch_modes_post(self) -> None:
        """Test case for fetch_auth_modes_v05_users_auth_fetch_modes_post

        Fetch Auth Modes
        """
        pass

    def test_fetch_consent_artefact_v05_consents_on_fetch_post(self) -> None:
        """Test case for fetch_consent_artefact_v05_consents_on_fetch_post

        Fetch Consent Artefact
        """
        pass

    def test_health_info_hiu_request_v05_health_information_hiu_on_request_post(self) -> None:
        """Test case for health_info_hiu_request_v05_health_information_hiu_on_request_post

        Health Info Hiu Request
        """
        pass

    def test_health_info_transfer_v05_health_information_transfer_post(self) -> None:
        """Test case for health_info_transfer_v05_health_information_transfer_post

        Health Info Transfer
        """
        pass

    def test_heartbeat_v05_heartbeat_get(self) -> None:
        """Test case for heartbeat_v05_heartbeat_get

        Heartbeat
        """
        pass

    def test_init_auth_v05_users_auth_init_post(self) -> None:
        """Test case for init_auth_v05_users_auth_init_post

        Init Auth
        """
        pass

    def test_init_consent_request_v05_consent_requests_init_post(self) -> None:
        """Test case for init_consent_request_v05_consent_requests_init_post

        Init Consent Request
        """
        pass

    def test_on_confirm_auth_v05_users_auth_on_confirm_post(self) -> None:
        """Test case for on_confirm_auth_v05_users_auth_on_confirm_post

        On Confirm Auth
        """
        pass

    def test_on_consent_request_status_v05_consent_requests_on_status_post(self) -> None:
        """Test case for on_consent_request_status_v05_consent_requests_on_status_post

        On Consent Request Status
        """
        pass

    def test_on_fetch_modes_v05_users_auth_on_fetch_modes_post(self) -> None:
        """Test case for on_fetch_modes_v05_users_auth_on_fetch_modes_post

        On Fetch Modes
        """
        pass

    def test_on_find_patient_v05_patients_on_find_post(self) -> None:
        """Test case for on_find_patient_v05_patients_on_find_post

        On Find Patient
        """
        pass

    def test_on_init_auth_v05_users_auth_on_init_post(self) -> None:
        """Test case for on_init_auth_v05_users_auth_on_init_post

        On Init Auth
        """
        pass

    def test_on_init_consent_request_v05_consent_requests_on_init_post(self) -> None:
        """Test case for on_init_consent_request_v05_consent_requests_on_init_post

        On Init Consent Request
        """
        pass

    def test_on_init_subscription_v05_subscription_requests_hiu_on_init_post(self) -> None:
        """Test case for on_init_subscription_v05_subscription_requests_hiu_on_init_post

        On Init Subscription
        """
        pass

    def test_patient_status_notify_v05_patients_status_notify_post(self) -> None:
        """Test case for patient_status_notify_v05_patients_status_notify_post

        Patient Status Notify
        """
        pass

    def test_patient_status_on_notify_v05_patients_status_on_notify_post(self) -> None:
        """Test case for patient_status_on_notify_v05_patients_status_on_notify_post

        Patient Status On Notify
        """
        pass

    def test_subscription_hiu_notify_v05_subscriptions_hiu_notify_post(self) -> None:
        """Test case for subscription_hiu_notify_v05_subscriptions_hiu_notify_post

        Subscription Hiu Notify
        """
        pass

    def test_subscription_notify_v05_subscription_requests_hiu_notify_post(self) -> None:
        """Test case for subscription_notify_v05_subscription_requests_hiu_notify_post

        Subscription Notify
        """
        pass


if __name__ == '__main__':
    unittest.main()
