# coding: utf-8

"""
    HIU API SDK

    Health Information User API for handling consent and health information requests.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from abdm-hiu-sdk.api.default_api import DefaultAPI


class TestDefaultAPI(unittest.TestCase):
    """DefaultAPI unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultAPI()

    def tearDown(self) -> None:
        pass

    def test_gateway_consent_request_notify(self) -> None:
        """Test case for gateway_consent_request_notify

        Notify HIU of consent changes via gateway
        """
        pass

    def test_gateway_consent_request_on_fetch(self) -> None:
        """Test case for gateway_consent_request_on_fetch

        Fetch consents from gateway
        """
        pass

    def test_gateway_consent_request_on_init(self) -> None:
        """Test case for gateway_consent_request_on_init

        Handle gateway consent request initialization
        """
        pass

    def test_gateway_health_information_on_request(self) -> None:
        """Test case for gateway_health_information_on_request

        Handle gateway health information request
        """
        pass

    def test_generate_consent_request(self) -> None:
        """Test case for generate_consent_request

        Generate a new consent request
        """
        pass

    def test_list_consent_artefacts(self) -> None:
        """Test case for list_consent_artefacts

        List consent artefacts
        """
        pass

    def test_list_consents(self) -> None:
        """Test case for list_consents

        List all consents
        """
        pass

    def test_receive_health_information(self) -> None:
        """Test case for receive_health_information

        Receive health information
        """
        pass

    def test_request_health_information(self) -> None:
        """Test case for request_health_information

        Request health information
        """
        pass

    def test_retrieve_consent(self) -> None:
        """Test case for retrieve_consent

        Retrieve a specific consent
        """
        pass

    def test_retrieve_consent_artefact(self) -> None:
        """Test case for retrieve_consent_artefact

        Retrieve a specific consent artefact
        """
        pass


if __name__ == '__main__':
    unittest.main()
