# coding: utf-8

"""
    HIU API SDK

    Health Information User API for handling consent and health information requests.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from abdm-hiu-sdk.abdm-hiu-sdk.model.gateway_consent_request_notify200_response_model import GatewayConsentRequestNotify200ResponseModel

class TestGatewayConsentRequestNotify200ResponseModel(unittest.TestCase):
    """GatewayConsentRequestNotify200ResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GatewayConsentRequestNotify200ResponseModel:
        """Test GatewayConsentRequestNotify200ResponseModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GatewayConsentRequestNotify200ResponseModel`
        """
        model = GatewayConsentRequestNotify200ResponseModel()
        if include_optional:
            return GatewayConsentRequestNotify200ResponseModel(
                message = 'Gateway consent request notify'
            )
        else:
            return GatewayConsentRequestNotify200ResponseModel(
        )
        """

    def testGatewayConsentRequestNotify200ResponseModel(self):
        """Test GatewayConsentRequestNotify200ResponseModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
