# coding: utf-8

"""
Health Repository Provider Specifications for HIU

The following are the specifications for the APIs to be implemented at the Health Repository end if an entity is only serving the role of a HIU. The specs are essentially duplicates from the Gateway and Bridge, but put together so as to make it clear to *HIUs* which set of APIs they should implement to participate in the network.     1. The APIs are organized by the flows - **identification**, **consent flow**, **data flow** and **monitoring**. They represent the APIs that are expected to be available at the HIU end by the Gateway.    2. For majority of the APIs, if Gateway has initiated a call, there are corresponding callback APIs on the Gateway. e.g for **/consents/hiu/notify** API on HIU end, its expected that a corresponding callback API **/consents/hiu/on-notify** on Gateway is called. Such APIs are organized under the **Gateway** label.    3. Gateway relevant APIs for HIUs are grouped under **Gateway** label. These include the APIs that HIPs are required to call on the Gateway. For example, to request a CM for consent, HIU would call **/consent-requests/init** API on gateway.    4. **NOTE**, in some of the API documentations below, **X-HIP-ID** is mentioned in header (for example in /auth/on-init). These are the cases, when a particular API is applicable for both HIU and HIP (e.g an entity is playing the role of HRP representing both HIU and HIP). If you are only playing the role of HIP, then only X-HIU-ID header will be sent

The version of the OpenAPI document: 0.5
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from abdm.abdm.model.consent_request_consent_model import ConsentRequestConsentModel


class TestConsentRequestConsentModel(unittest.TestCase):
    """ConsentRequestConsentModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConsentRequestConsentModel:
        """Test ConsentRequestConsentModel
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ConsentRequestConsentModel`
        """
        model = ConsentRequestConsentModel()
        if include_optional:
            return ConsentRequestConsentModel(
                purpose = abdm.models.use_purpose.UsePurpose(
                    text = '', 
                    code = '', 
                    ref_uri = '', ),
                patient = abdm.models.consent_request_consent_patient.ConsentRequest_consent_patient(),
                hip = abdm.models.consent_artefact_response_consent_consent_detail_hip.ConsentArtefactResponse_consent_consentDetail_hip(),
                care_contexts = [
                    abdm.models.care_context_definition.CareContextDefinition(
                        patient_reference = 'batman@tmh', 
                        care_context_reference = 'Episode1', )
                    ],
                hiu = abdm.models.consent_artefact_response_consent_consent_detail_hiu.ConsentArtefactResponse_consent_consentDetail_hiu(),
                requester = abdm.models.requester.Requester(
                    name = 'Dr. Manju', 
                    identifier = abdm.models.requester_identifier.Requester_identifier(
                        type = 'REGNO', 
                        value = 'MH1001', 
                        system = 'https://www.mciindia.org', ), ),
                hi_types = [
                    'OPConsultation'
                    ],
                permission = abdm.models.permission.Permission(
                    access_mode = 'VIEW', 
                    date_range = abdm.models.permission_date_range.Permission_dateRange(
                        from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        to = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    data_erase_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    frequency = abdm.models.permission_frequency.Permission_frequency(
                        unit = 'HOUR', 
                        value = 56, 
                        repeats = 56, ), )
            )
        else:
            return ConsentRequestConsentModel(
                purpose = abdm.models.use_purpose.UsePurpose(
                    text = '', 
                    code = '', 
                    ref_uri = '', ),
                patient = abdm.models.consent_request_consent_patient.ConsentRequest_consent_patient(),
                hiu = abdm.models.consent_artefact_response_consent_consent_detail_hiu.ConsentArtefactResponse_consent_consentDetail_hiu(),
                requester = abdm.models.requester.Requester(
                    name = 'Dr. Manju', 
                    identifier = abdm.models.requester_identifier.Requester_identifier(
                        type = 'REGNO', 
                        value = 'MH1001', 
                        system = 'https://www.mciindia.org', ), ),
                hi_types = [
                    'OPConsultation'
                    ],
                permission = abdm.models.permission.Permission(
                    access_mode = 'VIEW', 
                    date_range = abdm.models.permission_date_range.Permission_dateRange(
                        from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        to = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    data_erase_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    frequency = abdm.models.permission_frequency.Permission_frequency(
                        unit = 'HOUR', 
                        value = 56, 
                        repeats = 56, ), ),
        )
        """

    def testConsentRequestConsentModel(self):
        """Test ConsentRequestConsentModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
