# coding: utf-8

"""
    HIU API SDK

    Health Information User API for handling consent and health information requests.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from abdm-hiu-sdk.abdm-hiu-sdk.model.retrieve_consent200_response_model import RetrieveConsent200ResponseModel

class TestRetrieveConsent200ResponseModel(unittest.TestCase):
    """RetrieveConsent200ResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RetrieveConsent200ResponseModel:
        """Test RetrieveConsent200ResponseModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RetrieveConsent200ResponseModel`
        """
        model = RetrieveConsent200ResponseModel()
        if include_optional:
            return RetrieveConsent200ResponseModel(
                consent = abdm-hiu-sdk.models.retrieve_consent_200_response_consent.retrieveConsent_200_response_consent(
                    id = 56, )
            )
        else:
            return RetrieveConsent200ResponseModel(
        )
        """

    def testRetrieveConsent200ResponseModel(self):
        """Test RetrieveConsent200ResponseModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
