# coding: utf-8

"""
    HIU API SDK

    Health Information User API for handling consent and health information requests.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from abdm-hiu-sdk.abdm-hiu-sdk.model.list_consents200_response_model import ListConsents200ResponseModel

class TestListConsents200ResponseModel(unittest.TestCase):
    """ListConsents200ResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListConsents200ResponseModel:
        """Test ListConsents200ResponseModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListConsents200ResponseModel`
        """
        model = ListConsents200ResponseModel()
        if include_optional:
            return ListConsents200ResponseModel(
                consents = [
                    null
                    ]
            )
        else:
            return ListConsents200ResponseModel(
        )
        """

    def testListConsents200ResponseModel(self):
        """Test ListConsents200ResponseModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
