# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_gateway_consent_request_notify_your_gateway_callback_url_prefix_consents_hiu_notify_post(self) -> None:
        """Test case for gateway_consent_request_notify_your_gateway_callback_url_prefix_consents_hiu_notify_post

        Gateway Consent Request Notify
        """
        pass

    def test_gateway_consent_request_on_fetch_your_gateway_callback_url_prefix_consents_on_fetch_post(self) -> None:
        """Test case for gateway_consent_request_on_fetch_your_gateway_callback_url_prefix_consents_on_fetch_post

        Gateway Consent Request On Fetch
        """
        pass

    def test_gateway_consent_request_on_init_your_gateway_callback_url_prefix_consent_requests_on_init_post(self) -> None:
        """Test case for gateway_consent_request_on_init_your_gateway_callback_url_prefix_consent_requests_on_init_post

        Gateway Consent Request On Init
        """
        pass

    def test_gateway_health_information_on_request_your_gateway_callback_url_prefix_health_information_hiu_on_request_post(self) -> None:
        """Test case for gateway_health_information_on_request_your_gateway_callback_url_prefix_health_information_hiu_on_request_post

        Gateway Health Information On Request
        """
        pass

    def test_generate_consent_request_api_hiu_generate_consent_request_post(self) -> None:
        """Test case for generate_consent_request_api_hiu_generate_consent_request_post

        Generate Consent Request
        """
        pass

    def test_list_consent_artefacts_api_hiu_consent_artefacts_get(self) -> None:
        """Test case for list_consent_artefacts_api_hiu_consent_artefacts_get

        List Consent Artefacts
        """
        pass

    def test_list_consents_api_hiu_consents_get(self) -> None:
        """Test case for list_consents_api_hiu_consents_get

        List Consents
        """
        pass

    def test_receive_health_information_api_hiu_health_information_receive_post(self) -> None:
        """Test case for receive_health_information_api_hiu_health_information_receive_post

        Receive Health Information
        """
        pass

    def test_request_health_information_api_hiu_health_information_request_post(self) -> None:
        """Test case for request_health_information_api_hiu_health_information_request_post

        Request Health Information
        """
        pass

    def test_retrieve_consent_api_hiu_consents_pk_get(self) -> None:
        """Test case for retrieve_consent_api_hiu_consents_pk_get

        Retrieve Consent
        """
        pass

    def test_retrieve_consent_artefact_api_hiu_consent_artefacts_pk_get(self) -> None:
        """Test case for retrieve_consent_artefact_api_hiu_consent_artefacts_pk_get

        Retrieve Consent Artefact
        """
        pass


if __name__ == '__main__':
    unittest.main()
